[tool.poetry]
name = "from-the-tensor"
version = "0.1.0"
description = ""
authors = ["Jacky Lee <jla524@sfu.ca>"]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.27.1"
numpy = "^1.22.3"
torch = "^1.11.0"
ale-py = "^0.7.5"
gym = {extras = ["accept-rom-license"], version = "^0.23.1"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
